### PR TITLE
add getTemplate, add getter for PadTemplate, add PadTemplateTest

### PR DESCRIPTION
**Pull request by i-n-g-o**
actually i'm not sure about how to get template-name, direction, presence. there might be a better solution for this. maybe getting the data from the lowlevel structure to avoid this ugly casting stuff...
it works though.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Can you rebase (or reopen) against master?  Got a merge conflict with your other PR.  Thanks!

**Comment by i-n-g-o** [comment]
yes, sure.

**Comment by i-n-g-o** [comment]
should be fine to merge now

**Comment by neilcsmith-net** [comment]
Thanks!  Will merge.  Not sure that I like the number to enum conversion, but can't think of a nicer way at the moment - will have a look later.

**Pull request merged**
