### PR TITLE
add Meta classes

### PR DESCRIPTION
**Pull request by lafoletc**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks!  Need to have more of a look at this one.  I don't like exposing `GType` or `Pointer` in the public facing API.  In fact, I'd like to remove or deprecate the ones we have before we release 1.0.

Instead of `GType` we should be using classes, which would also remove the generics issue.  Maybe something based on the existing subtype mappers?

**Comment by lafoletc** [comment]
For method Buffer.getMeta(final GType api), gst_buffer_get_meta() need a GType.
We could replace parameter "GType api" by its string and retrieve the GType with GType.valueof(string) but it's not a could idea to deal with string

**Comment by lafoletc** [comment]
I have make a try with classes : 
For example with
public class VideoMeta extends Meta {
    public static final String GTYPE_NAME = "GstVideoMeta";
    public static final String GTYPE_API_NAME = "GstVideoMetaAPI";
...
}
We would need to add a second string identifier to specify the api and put in a cache the GType api for a class

**Comment by neilcsmith-net** [comment]
Possibly. We might need the caching but not sure we need to expose the `GTYPE` fields.  I've been thinking about mechanisms for type registration so that we allow the library to be extended from outside more easily.

Another option here I guess would be to have a `Meta.Type<? extends Meta>` class that encapsulates the `GType` info in a type-safe way.

So that you have

`public <T extends Meta> T getMeta(Meta.Type<T> type)`

called like

`VideoMeta videoMeta = getMeta(VideoMeta.TYPE);`

**Comment by neilcsmith-net** [comment]
Adding a note that this will also require fixing for the GType size issue before merging.

**Comment by MaZderMind** [comment]
This PR is also lacking some Unit-Tests for the new API.

**Comment by neilcsmith-net** [comment]
@MaZderMind yes, the whole thing needs rewriting for post-v1.  It's kept open so can discuss or start from scratch on that.

**Comment by neilcsmith-net** [comment]
OK, going to close this. Hopefully all functionality here, and more, is covered in #208 . Next step is to add proper wrapper classes for other metas.

**Pull request closed without merging**
