### PR TITLE
add Utility Functions, GlibUtils and GlibUtilsTest

### PR DESCRIPTION
**Pull request by i-n-g-o**
adding environment utilities (handy to have)

### CODE REVIEW

**Comment by woglinde** [comment]
There is a small typo in the commit msg "GlubUtils".

**Comment by i-n-g-o** [comment]
i saw the typo when creating this PR and corrected it there.
does it matter?

**Comment by neilcsmith-net** [comment]
Well, there's a different typo :smile: - it should be GLib - so GLibUtils, although possibly just call the class GLib?

I've been wondering about adding this, but wondered whether recommending JNA Platform made more sense.  One thing I use JNA Platform for is altering the path env variable on Windows before this is loaded, although jna.library.path might work as well for that.

Might as well have this in, anyway - thanks.  If you can correct the class names I'll merge.

**Comment by i-n-g-o** [comment]
ah now. finally i found these functions in jna-platform 😁
anyway. renamed the classes to GLib and GLibTest

**Pull request merged**
