### PR TITLE
GType.valueof(string) should raise IllegalStateException for an unregistered GType

### PR DESCRIPTION
**Pull request by lafoletc**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks, but why?  Surely if the response is GType.INVALID, that's what should be returned?

**Comment by lafoletc** [comment]
GType.INVALID seems to be a valid GType and nobody verify the result for method returning GType (nor in gstreamer source nor in user source). I have still made the error several times.
If GType.valueof return an invalid result, that means the GType is not registered yet, so exception is not absurd.

**Comment by neilcsmith-net** [comment]
Yes, see what you mean. I'm usually a bit wary of changing underlying behaviour to be more Java like as sometimes it masks something. OK, probably need to document this if it's theoretically public, and I wonder whether IllegalArgumentException is more correct?  That mirrors the related method.

**Comment by neilcsmith-net** [comment]
Closing this - will need rethinking as and when some form of GType wrapper is exposed outside of lowlevel.

**Pull request closed without merging**
