### PR TITLE
Pipeline launch log error

### PR DESCRIPTION
**Pull request by i-n-g-o**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for this!  Agree with the need to not hide this, but disagree with this solution.  I think we need to find a way to give the error back to the caller, but not sure of the best API to do that.  Possibly something along the lines of 

```java
Pipeline.launch(String description, List<String> errors);
```

???

Could also be a chance to move this into Gst.  Don't like the confusion with the same named method in Bin.

So, possibly -

```java
Pipeline Gst.parseLaunch(String description, List<String> errors);
Bin Gst.parseBinFromDescription(String description, List<String> errors);
```

**Comment by i-n-g-o** [comment]
yes, agree. would be better to give the error back to the caller.
for completeness we could use a GError instead of String?

```java
Pipeline.launch(String description, List<GError> errors);
```

also agree to move it into Gst and aligning with gstreamer-function names

**Comment by i-n-g-o** [comment]
Pipeline.initBus() is used after creating the pipeline. it is a private function with comments but without any functionality.
guess this works now and is safe to remove?

**Comment by i-n-g-o** [comment]
when passing the error-list to launch(String...) with varargs it would need to look like this:

```java
Pipeline.launch(List<GError> errors, String... pipelineDecription);
```

better to pass the error-list as first argument then? - that's weird too...

**Comment by neilcsmith-net** [comment]
I wouldn't assume it's a no-op too quickly!  Am wondering why it's not in the constructor there though?!

**Comment by neilcsmith-net** [comment]
Or the new version could be `String[]`?  Or we don't have a new version with `String ...`?

**Comment by i-n-g-o** [comment]
initBus() is actually called in the contructor... so that's fine.

**Comment by neilcsmith-net** [comment]
Not in the one that takes an `Initializer`, which should be the one that gets called here.  Need to dig a bit more into that, and also whether `getBus()` and specifically the `Bus` constructor is doing something that needs to happen.

Short version - let's leave it for now!

**Comment by neilcsmith-net** [comment]
Thanks!  Will pull this in but may rethink the API a little more before next release.

**Comment by i-n-g-o** [comment]
should the launch() functions in Bin/Pipeline be removed?
(removed them but did not push...)

about the pipeline-constructor: question is why `initBus()` is not called in the constructor which takes the `Initializer`...?
if we would move it in there all constructors would call `initBus()`

**Comment by neilcsmith-net** [comment]
I will (probably) deprecate rather than remove the launch() methods for now, with aim to remove before 1.x.

I need to look deeper at the `initBus()` thing - need to look at any other uses of that constructor first, which will be hidden in native bindings.

**Comment by i-n-g-o** [comment]
yes. deprecating first...
i will offer another PR which changes BinTest and PipelineTest to use the new functions in Gst.

**Pull request merged**
