### PR TITLE
Add API for gst_element_link_filtered

### LINKED ISSUE #150: gst_element_link_filtered is missing from Element-API
Support for `gst_element_link_filtered`  is missing from the `Element`-API.

### PR DESCRIPTION
**Pull request by MaZderMind**
Fixes #150

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Looks good, thanks, and I see you force pushed whatever caused Travis to break initially.  I'll merge soon.

**Comment by MaZderMind** [comment]
I forgot a file which resulted in the build failing. I then amended the missing file into the commit which made the build green again.

**Comment by neilcsmith-net** [comment]
Thanks, and sorry for the delay in merging.

**Comment by MaZderMind** [comment]
@neilcsmith-net Any Idea when you might be able to tag & release an 1.1? Thanks in advance!

**Comment by neilcsmith-net** [comment]
I have some funded work to complete on #158 Controller API support, so will be another week or two. Sorry for the delay. Thanks!

**Comment by MaZderMind** [comment]
@neilcsmith-net Oh, nice that you get paid for at least part of this API binding. Thank you for your feedback and no worries - I know how it feels to maintain an OpenSource project.

**Pull request merged**
