### PR TITLE
gst_date_time_get_type() shall not be associated with GDate

### PR DESCRIPTION
**Pull request by lafoletc**
GDate have its own gtype.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks, pulling!

**Comment by neilcsmith-net** [comment]
This seems to be missing some changes to GstTagListAPI?  Doesn't build - reverted for now.

**Comment by lafoletc** [comment]
Hello Neil,
Sorry for GstTagListAPI, file was missing from my pull request

I have made a new request here https://github.com/lafoletc/gst1-java-core/commit/e37cd7fa7e2d6f4d0ce11445e16c64e7e9a9f7f8

**Comment by neilcsmith-net** [comment]
Hi, No problem, but any chance you could make a whole new pull request for everything?  Or any idea how to merge an already merged and reverted pull request? :confused:

**Comment by lafoletc** [comment]
Hi,
could you please take into account https://github.com/gstreamer-java/gst1-java-core/pull/65
I will redo a commit if necessary

**Comment by neilcsmith-net** [comment]
Hi,

Ideally, can you do a new pull request that covers this and #65 ?  I'd rather merge it all in cleanly together, and am not sure how to re-merge this anyway.

Thanks, Neil

**Comment by lafoletc** [comment]
ok I have renamed and completed https://github.com/gstreamer-java/gst1-java-core/pull/65
I close this PR

**Comment by neilcsmith-net** [comment]
Thanks.  I'll look to merge that ASAP.  This PR is effectively closed anyway as it was merged and then reverted.

**Pull request merged**
