### PR TITLE
Prevent exception in constructor of GValueArray

### PR DESCRIPTION
**Pull request by lafoletc**
Add check with null pointer
Due to method Structure.validate(), an exception was raised when JNA try to invoke constructor of GValueArray with "new Pointer(0)"

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks.  But why should we protect against this?  Is there a particular concern you're trying to address?

Also, JNA already has `Pointer.NULL` and/or `Pointer.nativeValue(Pointer p)`

**Comment by lafoletc** [comment]
I have tried to use interface Decodebin.AUTOPLUG_FACTORIES and JNA instanciate a default result using on Pointer(0), that raise an exception

**Comment by neilcsmith-net** [comment]
That sounds like our problem not JNA. More likely the type mapper needs updating to handle null (Pointer.NULL) results?

**Comment by lafoletc** [comment]
In case of function, JNA try to call the constructor with Pointer as argument to verify if it will be able to convert thé C result in Java object , and use a default pointer on 0

**Comment by lafoletc** [comment]
I agree with your idea : why create a Java object if the pointer address is 0 ?
Why not returning a null Java object ?
Is it compatible for all cases ?

**Comment by lafoletc** [comment]
"type mapper" can not help us : it is use to convert object between Java and C.
Here, we are in full Java
See method Structure.validate() => Structure.newInstance(cls, PLACEHOLDER_MEMORY)

**Comment by neilcsmith-net** [comment]
Ah, OK, thanks.  Missed the context of where this was coming from.  Confused by the fact that we're registering this class in our type mapper - that needs looking at, but it's nothing to do with this then.  Couple that with the fact I'd misread from the JavaDoc that `Pointer.NULL` was `new Pointer(0)` when it's just `null`.  Sorry, I failed all around on this one! 😞 

I'll pull this in ASAP.

**Pull request merged**
