### PR TITLE
Fix Caps API

### PR DESCRIPTION
**Pull request by matthiasblaesing**
- Reenabled the unittests for Caps
- Fixed API bindings
- Fixed Caps wrapper

### CODE REVIEW

**Comment by lafoletc** [comment]
hello,
are you sure that for gst_caps_merge (caps1, caps2), caps1 should be @Invalidate ?
I don't see this in https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstCaps.html#gst-caps-merge
Regards

**Comment by matthiasblaesing** [comment]
Hey,

my reading is this:

- both inputs transfer ownership when they are used as input to the function
- the result can be the original structure _or_ a writeable copy of the structure
- the result is owned by the caller

from the POV of the runtime a new object emerges (invalidating the old one).

Greetings, Matthias

**Comment by lafoletc** [comment]
my reading is :  Caps1 is not modifiable, only Caps2 is freed, the result is issued from a copy of Caps1
if you set Caps1 @Invalidate, you could not use the current Caps object any more.

**Comment by matthiasblaesing** [comment]
Could you describe why you interpret it this way? Both parameters are marked as `transfer full`. This is in contrast to the `gst_caps_append`, which explicitly does not return anything, but modifies the first element. 

From the documentation of `gst_caps_merge`:

>  they are transferred to a **writable copy** of caps1

Together with the `transfer full` marks, this results in invalidating the original object.

**Comment by lafoletc** [comment]
ok 
I have not seen the  transfer full for both

**Comment by matthiasblaesing** [comment]
@lafoletc this is a followup to the email discussion. Instead of trying to do a partial structure mapping I opted to leave the native side mostly alone.

I removed the caps structures and replaced the  GstStaticPadTemplate structure with a PointerType. The three relevant members of the structure are accessed by direct memory reads and the embedded GstCaps are accessed via the api method.

With the latter change ElementFactoryTest runs clean apart from the GarbadgeCollection tests.

**Comment by matthiasblaesing** [comment]
This commit is based on the PR:

https://github.com/gstreamer-java/gst1-java-core/pull/25

So if that should not be merged, please don't merge this.

**Pull request merged**
