### PR TITLE
AppSink : newPreroll and newSample shall return a FlowReturn

### PR DESCRIPTION
**Pull request by lafoletc**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
I'm torn on this one.  This fix would break a lot of common usage.  On the other hand, doing this before a full v1 release makes sense, and the other ways of addressing this without breaking existing code are ugly.

I'm am confused why anyone has seen issues with this though - JNA should return 0 (so FlowReturn.OK) with void anyway?!

**Comment by lfarkas** [comment]
i'm vote for this changes even if it's break somthing.

**Comment by lafoletc** [comment]
I propose to rename the method NEW_SAMPLE.newBuffer() in NEW_SAMPLE.newSample().

**Comment by neilcsmith-net** [comment]
@lafoletc yes, agree with that.  Let's do it!  Now is the time to break stuff, as I'd like to get us to 1.0 sometime soon.

Can you add to this pull request?

Thanks, Neil

**Comment by lafoletc** [comment]
Done

**Comment by neilcsmith-net** [comment]
OK, let's break everyone's code! :smile_cat:

**Pull request merged**
