### PR TITLE
Add Playbin-methods to query/set current of audio/text stream.

### PR DESCRIPTION
**Pull request by sviperll**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thank! Looks useful. A few comments before I can pull though.

- please remove the whitespace change in GObject - no other change in that file?
- `Pad.objectFor()` is weird. Can you not just use `objectFor()`?  Or use `NativeObject.objectFor()`
- have you checked there isn't a memory leak here?  Sure it shouldn't be `objectFor(result, Pad.class, false)`?  Depends if the returned object is transfer full.

Also, looking at the repeated code you have in the signal methods it might be worth adding a variation of `emit()` in GObject that does all that and returns the right type?

eg. something like `public <T> T emit(Class<T> type, String signal, Object... arguments)`;  Any thoughts?

Thanks, Neil

**Comment by sviperll** [comment]
> Thank! Looks useful. A few comments before I can pull though.
>
>  * please remove the whitespace change in GObject - no other change in that file?

Yes, sorry for this, I've created pull-request on Windows machine and it's still uncomfortable...

> * Pad.objectFor() is weird. Can you not just use objectFor()? Or use NativeObject.objectFor()

I've checked NativeObject.objectFor and it got an impression that it's better to use explicit type... May be I'm wrong...

>  * have you checked there isn't a memory leak here? Sure it shouldn't be objectFor(result, Pad.class, false)? Depends if the returned object is transfer full.

Sorry, I've thought about it, but I've decided to investigate ownership transfer contract later... and forgot about it... Besides I'm not very well versed with GObject-ownership model and it's implementation in `gst1-java-core`'s NativeObject/MiniObject. And I'm afraid I'm not qualified enough to manually check for memory leak between java and C-code.

> Also, looking at the repeated code you have in the signal methods it might be worth adding a variation of emit() in GObject that does all that and returns the right type?
>
> eg. something like public <T> T emit(Class<T> type, String signal, Object... arguments); Any thoughts?

That was my first instinct, but I've rejected it at last since

 * I wasn't sure about ownership contract and decided that
 * each signal should be handled with special care since it's too easy to get it wrong when interface is deceptively simple and
 * it's better to stay close to C-API to facilate Java-development with C-documentation :)

I think we should get ownership transfer-story right at first and then such method can be added...

**Comment by sviperll** [comment]
I've finally implemented most of your suggestions almost literally. Still I'm not sure about

````
            return NativeObject.objectFor(result, resultType, false, true);
````

but it's seems the most safe alternative, as I see it after reading GObject documentation and `gst1-java-core`'s source code...

**Comment by neilcsmith-net** [comment]
Thanks for this!  Looks great.  Sorry for the delay - tied up with a conference.  I'll look to pull in ASAP.

With regards to `NativeObject.objectFor()`, it's just good practice to refer to static methods via the class they're defined in.  Nothing specific to this project.

**Pull request merged**
