### PR TITLE
Add AllocationQuery

### PR DESCRIPTION
**Pull request by lafoletc**
Force the update of GstBaseSinkStruct and GstBaseSinkClass

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for this.  Please can you revert the re-ordering of import statements and then I'll look to pull in.

**Comment by lafoletc** [comment]
I m on holidays
I will do ASAP

**Comment by neilcsmith-net** [comment]
Not a problem. No rush - enjoy your holidays. 😄 Sorry for the delay in looking at it - it's only because it is the holidays I have a little time at the moment.

**Comment by lafoletc** [comment]
Done for Gst.java
Christophe

**Comment by neilcsmith-net** [comment]
Thanks.  Pulling in now.

**Pull request merged**
