### PR TITLE
Feature/gathering state

### PR DESCRIPTION
**Pull request by PertsevRoman**
IceGathering state getter; tests; may be useful for state monitoring

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks!  I'll look to merge for 1.1 release - hopefully in a few weeks when Controller API is complete.

**Comment by neilcsmith-net** [comment]
Hi @PertsevRoman can you take a quick look why GitHub is complaining about this PR being out of date with the base branch?  Perhaps because of the merged PR?  The Controller API work is good to go, so will aim to roll v1.1 before the end of the week.  Be good to get this in.

**Comment by PertsevRoman** [comment]
Hello @neilcsmith-net , unfortunatelly I will be able to review the PR tomorrow only.

**Comment by neilcsmith-net** [comment]
@PertsevRoman no problem - still awaiting feedback on a few things, so sometime this week would be great!  I'm pretty sure I can just squash and merge this if need be, but a quick check over from you would be useful.

**Comment by PertsevRoman** [comment]
@neilcsmith-net , ok, merge completed successfully. Thanks for your waiting!

**Comment by neilcsmith-net** [comment]
Thanks, merged!

**Pull request merged**
