### PR TITLE
Update devel branch from master

### PR DESCRIPTION
**Pull request by isaacrj**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@isaacrj I assume this was a mistake?!  Merging the other way?  A few things in that list look like they might be useful PRs in future though!

**Comment by isaacrj** [comment]
Yes, I was trying to merge the other way around. 
I totally intend to do some PRs of this code, but I need to resolve some conflicts on my end first, as the code can not be automatically merged as it is.

**Comment by isaacrj** [comment]
There are a lot of commits on this list, though, which ones do you think that could be most interesting? I would prioritize preparing PRs for those.

**Comment by neilcsmith-net** [comment]
@isaacrj things that extend the existing classes, are related to core/base functionality, fix getting data in and out of GObjects, etc. would be great.

Elements (particularly any not in base) I don't want to merge here, but we could consider a separate repo for.  The libnice stuff should probably be a separate repo too?  In hindsight, webrtc should have been!

**Pull request closed without merging**
