### PR TITLE
Changes for pad/caps methods renamed from 0.10 to 1.0

### PR DESCRIPTION
**Pull request by smarquard**
As per migration guide:

https://cgit.freedesktop.org/cgit/?url=gstreamer/gstreamer/plain/docs/random/porting-to-1.0.txt

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for this.  Will check through and merge ASAP.

**Comment by smarquard** [comment]
Just following up on this - any concerns?

I'm working on a java app using gstreamer (lecturesight.org, https://opencast.jira.com/browse/LS-164) which needs this change, and ideally a release of gst1-java-core in a maven repo, to migrate from gstreamer 0.x to 1.x.

**Comment by neilcsmith-net** [comment]
On 19 Apr 2016 10:11, "Stephen Marquard" <notifications@github.com> wrote:
> Just following up on this - any concerns?

No concerns, just a time issue over the last month. I'll pull this in this
week. Thank you!

Longer term, I'll probably set up a separate development branch to pull
changes in quicker while attempting to keep master stable.

On the Maven front, are you on the mailing list? There was a request for
help in getting the configuration fixed to push centrally. Please open an
issue (or pull request) on that.

Thanks, Neil

**Comment by smarquard** [comment]
Thanks (and for getting this project off the ground!). I did see your note about maven. My maven knowledge is rather limited, but I'm checking to see if there's anyone else involved in Lecturesight who can help out.

**Comment by neilcsmith-net** [comment]
OK, sorry about how long this has taken.  Just read through the documentation (but not tested) and going to merge now. After this, we should probably deprecate getNegotiatedCaps() and add getCurrentCaps(), and also provide a version of getCaps() that accepts the filter.

Thanks for bearing with me! :smile:

**Pull request merged**
