### PR TITLE
GQuark.valueOf() shall be a static method

### PR DESCRIPTION
**Pull request by lafoletc**

### CODE REVIEW

**Comment by lafoletc** [comment]
.

**Comment by lfarkas** [comment]
the same already applied to the 0.10 binding.

**Comment by lafoletc** [comment]
ok for Gstreamer-java 
but not applied for gst1-java-core
Regards

**Comment by neilcsmith-net** [comment]
Hi @lafoletc Thanks for these.  I thought I'd commented on this via email when it was originally opened, but can't see that. Did you receive anything? Please can you put these up as separate pull requests.  I don't want to merge those changes together.  In particular, I want to look at the AppSink commit separately as it might cause breaking issues - agree it needs to be changed mind you!

Thanks.

**Comment by lafoletc** [comment]
ok, I have removed changes.
I open separate pull requests for TagList and Appsink.

**Comment by neilcsmith-net** [comment]
Thanks!

**Pull request merged**
