### PR TITLE
webrtcstate cast fix; add .idea catalog to gitignore; some doc fixes;

### PR DESCRIPTION
**Pull request by PertsevRoman**
Based on https://stackoverflow.com/questions/5878952/cast-int-to-enum-in-java

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks!  We shouldn't really use `values()` for this though. even if it might be correct in this specific case.  It should be based on the `NativeEnum.intValue()`.  And we should probably add a static utility method similar to those in `NativeFlags` to get the value from an int so it's all in one place.

**Comment by PertsevRoman** [comment]
Shall I add this static method to WebRTCPeerConnectionState?

**Comment by neilcsmith-net** [comment]
Sorry, should have been clearer - the static method should go in `NativeEnum`. See ..

- https://github.com/gstreamer-java/gst1-java-core/blob/master/src/org/freedesktop/gstreamer/glib/NativeEnum.java
- https://github.com/gstreamer-java/gst1-java-core/blob/master/src/org/freedesktop/gstreamer/glib/NativeFlags.java#L36

Ideally this would probably be called `fromInt()` but not sure about the static hiding that will entail?!  It'll be something like 

```java
public static <T extends Enum<T> & NativeEnum<T>> T
            fromInt(Class<T> type, int intValue) {
  for (T value : type.getEnumConstants()) {
    if (value.intValue() == intValue) {
      return value;
    }
  }
  throw new IllegalArgumentException(); // or return null?
}
```

**Comment by PertsevRoman** [comment]
I added one test for completely checking

**Comment by neilcsmith-net** [comment]
The fix for the issue looks OK, thanks, but this shouldn't be touching 141 files!  Please reopen another PR with just the fix in it and I'll look at merging.  The formatting and import changes won't be merged.

**Comment by PertsevRoman** [comment]
Solved in https://github.com/gstreamer-java/gst1-java-core/pull/154

**Pull request closed without merging**
