### PR TITLE
Add interfaces DEEP_ELEMENT_ADDED and DEEP_ELEMENT_REMOVED to Bin

### PR DESCRIPTION
**Pull request by lafoletc**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks.  There may be a meta-issue to consider with this - how to properly handle API added by GStreamer in such a way that we don't cause issues for people mapping to lower versions?

**Comment by lafoletc** [comment]
Yes,
Compatibility is a global problem

**Comment by matthiasblaesing** [comment]
I suggest to map all methods and mark the methods with the `since` javadoc tag and use the minimum gstreamer version as the value.

In the end the user of the function has to make sure that a recent enough gstreamer version is installed.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing yes, that might be the way to do it but it pushes a problem downstream that might be better handled here. Bear in mind if we ever switch to direct mappings, this will fail with a link error for any use of the whole class so we'd be forced to handle it differently.  Even with what we have it will throw an error (not an exception) on use of the function.

**Comment by matthiasblaesing** [comment]
@neilcsmith-net for direct mapping: You could consider implementing a subset of the methods as native methods and let the less important (and newer ones) take the reflective route.

In general I'd try to keep up with the native library. If the developer decides to use a method added in the native library in version 1.10 and the user 1.8 this will error out, just as it would do with a C programm. If I'm not mistaken a C programm will fail runtime linking, while a java programm could catch the UnsatisfiedLinkError, that is thrown.

In the java space there is already a similar situation: JDBC. Most drivers implement a subset and you basicly have to live with the fallout, or know your target driver/version.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing thanks, yes have taken that approach before in another JNA library. I'm just wondering of better approaches. Things like how JOGL approaches profiles perhaps (ie. using the type system), or runtime introspectable annotations.  This also potentially affects how we approach tests - the source project should at least be buildable against a lower version of GStreamer.

**Comment by lafoletc** [comment]
some methods can be declared in our API binding interface but not present in C. 
this do not seems to raise an error when JNA do the binding but raise UnsatisfiedLinkError when the user invoke the method.
It's the user responsability to verify which method is valid with the gstreamer release.
Ex: GstCapsAPI.gst_caps_make_writable() is still present (it is a mistake) and should be removed

**Comment by neilcsmith-net** [comment]
Going to merge this.  I have some thoughts on using a mix of asserts and annotations for upstream versioning, but I'll open an issue for discussing that.  This is not just about user responsibility - it might affect how we test too.  Also will open a meta issue for things like the GstCapsAPI method - there's a range of things that need pulling out before 1.0.

Thanks!

**Pull request merged**
