### PR TITLE
align structures for BaseSink, BaseSrc

### PR DESCRIPTION
**Pull request by i-n-g-o**
hi.
i had some time and started checking the lowlevel structures.
will try to continue this in a slow pace doing one by one...

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for starting this job!  Somewhere, comment here or maybe in a readme in lowlevel or in the JavaDoc (thoughts?), could you list the structures as you do them and include a link to the relevant upstream code repo?  Could be the GitHub mirror or on freedesktop I guess.

**Comment by i-n-g-o** [comment]
oh sure, good idea.
i think a link to the original version 1.8 header-file in the javadoc makes sense, the classes have to be revisited at least another time to align functions.

i started with "a" and proceed alphabetically, will add a readme in lowlevel and list classes i have done so far with the next push.

**Comment by neilcsmith-net** [comment]
Can I merge this work so far?  Thanks, Neil

**Comment by i-n-g-o** [comment]
sure. the changes should be fine so far.

**Comment by neilcsmith-net** [comment]
OK, cool!  Had tested but wanted to check with you too. Having a pre-conference surge in activity! :smile:

**Comment by i-n-g-o** [comment]
hehe, nice. :D
well, this work should be finished sometimes...

**Comment by i-n-g-o** [comment]
did you continue the structure cleanup?
or should we use this branch to follow things up?
(you mean gst-conference 25/26 i guess?)

**Comment by neilcsmith-net** [comment]
@i-n-g-o emailed you re. conference.  Yes, please do continue with this branch if you're happy to follow up.  I'm looking at some other public API things, so not looking at these currently unless they break something outside of lowlevel.  Thanks!

**Pull request merged**
